### ISSUE TITLE
TypeError:sss.playMml is not a function

### ISSUE THREAD

**Issue by cc54294** [abagames/sounds-some-sounds#1]
use typescript

npm i sounds-some-sounds

import * as sss from "sounds-some-sounds";
sss.playMml(bmgArray)

get error:
Uncaught (in promise) TypeError: sss.playMml is not a function

**Comment by abagames** [comment]
The minimum sample code to use playMml is shown below; if you use it in TypeScript, please use it in combination with a bundler such as Vite.
```typescript
import * as sss from "sounds-some-sounds";
addEventListener("load", () => {
  sss.init(42);
});
addEventListener("click", () => {
  sss.startAudio();
  sss.playMml(["cdef"]);
  update();
});
function update() {
  requestAnimationFrame(update);
  sss.update();
}
```
